name: drift_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  flutter_bloc: ^8.1.1
  auto_route: ^8.2.0
  flutter_local_notifications: ^17.1.2
  drift: ^2.18.0
  provider: ^6.1.2
  intl: ^0.19.0
  freezed_annotation: ^2.0.0
  json_annotation: ^4.3.0
  sensors_plus: ^5.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  geolocator: ^12.0.0
  flutter_sensors: ^1.0.1
  flutter_localizations:
    sdk: flutter
  
  shared_preferences: ^2.2.3
  intl_utils: ^2.8.7
 

dev_dependencies:
  mockito: ^5.4.4
  auto_route_generator: ^8.0.0
  build_runner: ^2.1.0
  freezed: ^2.0.0
  json_serializable: ^6.1.0
  intl_translation: ^0.20.0


flutter:
  generate: true
  assets:
    - assets/images/
  uses-material-design: true
fflutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated

