// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2g1XJY9w2M-aCnEvweDgAthhsqP3UDwA',
    appId: '1:299030933687:web:96fff5717d86c378031d32',
    messagingSenderId: '299030933687',
    projectId: 'drift-478f4',
    authDomain: 'drift-478f4.firebaseapp.com',
    storageBucket: 'drift-478f4.appspot.com',
    measurementId: 'G-Y4MQJJGRZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwLSobGkPnndNZegFwRHUZL0LNZICmaI',
    appId: '1:299030933687:android:80823e6c5e3abeed031d32',
    messagingSenderId: '299030933687',
    projectId: 'drift-478f4',
    storageBucket: 'drift-478f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6yHbXb220eyL3BShe03GFRgtyrHQYqs',
    appId: '1:299030933687:ios:fdf4480058372648031d32',
    messagingSenderId: '299030933687',
    projectId: 'drift-478f4',
    storageBucket: 'drift-478f4.appspot.com',
    iosBundleId: 'com.example.driftTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6yHbXb220eyL3BShe03GFRgtyrHQYqs',
    appId: '1:299030933687:ios:fdf4480058372648031d32',
    messagingSenderId: '299030933687',
    projectId: 'drift-478f4',
    storageBucket: 'drift-478f4.appspot.com',
    iosBundleId: 'com.example.driftTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2g1XJY9w2M-aCnEvweDgAthhsqP3UDwA',
    appId: '1:299030933687:web:9cb3f048c56c0302031d32',
    messagingSenderId: '299030933687',
    projectId: 'drift-478f4',
    authDomain: 'drift-478f4.firebaseapp.com',
    storageBucket: 'drift-478f4.appspot.com',
    measurementId: 'G-N9LMEEZ74S',
  );
}
